import type { BotConfig } from '../types'

export const bots: BotConfig[] = [
  {
    id: 'pelle',
    name: 'Pelle',
    rating: 400,
    description: 'Nybörjare som gärna blundrar bort pjäser',
    avatar: '🐣',
    depth: 1,
    moveTime: 200,
    skillLevel: 1,
  },
  {
    id: 'britta',
    name: 'Britta',
    rating: 800,
    description: 'Hobbispelare som gillar enkla taktiker',
    avatar: '🎯',
    depth: 4,
    moveTime: 300,
    skillLevel: 4,
  },
  {
    id: 'oskar',
    name: 'Oskar',
    rating: 1200,
    description: 'Klubbspelare med solida grundkunskaper',
    avatar: '♟️',
    depth: 8,
    moveTime: 500,
    skillLevel: 8,
  },
  {
    id: 'astrid',
    name: 'Astrid',
    rating: 1600,
    description: 'Stark spelare med bra positionskänsla',
    avatar: '⚔️',
    depth: 12,
    moveTime: 800,
  },
  {
    id: 'viktor',
    name: 'Viktor',
    rating: 2000,
    description: 'Mästare som hittar djupa kombinationer',
    avatar: '🏆',
    depth: 16,
    moveTime: 1000,
  },
  {
    id: 'fischer',
    name: 'Fischer',
    rating: 2500,
    description: 'Legendarisk motståndare — full styrka',
    avatar: '👑',
    depth: 22,
    moveTime: 2000,
  },
]
